inherit_from: .rubocop_todo.yml

require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - docs/**/*
    - script/**/*
    - test/**/*
    - vendor/**/*
    - Rakefile
Style/MutableConstant:
  Exclude:
    - lib/jekyll-import/importers/typo.rb
