#!/usr/bin/env ruby
# frozen_string_literal: true

STDOUT.sync = true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "jekyll-import"
require "jekyll-import/version"
require "jekyll/commands/import"
require "mercenary"

Mercenary.program(:jekyll_import) do |p|
  p.version JekyllImport::VERSION
  p.description "Import from various blogs to Jekyll format."
  p.syntax "jekyll-import <blog_engine> [options]"

  # Create all the subcommands for the importers.
  JekyllImport.add_importer_commands(p)

  p.action do |args, _|
    if args.empty?
      Jekyll.logger.error "An importer subcommand is required."
      Jekyll.logger.info p
      abort
    else
      subcommand = args.first
      unless p.has_command? subcommand
        Jekyll.logger.abort_with "fatal: 'jekyll-import #{args.first}'" \
          " could not be found."
      end
    end
  end
end
