title: "jekyll-import • Import your old &amp; busted site to Jekyll"
url: https://import.jekyllrb.com
highlighter: rouge
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
repository: https://github.com/jekyll/jekyll-import
latest_release: 0.24.0

collections:
  docs:
    output: true
  importers:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      type: docs
    values:
      layout: docs
  - scope:
      type: importers
    values:
      layout: importer

sass:
   style: compressed
