title: "jekyll-import • Import your old &amp; busted site to Jekyll"
url: https://import.jekyllrb.com
repository: https://github.com/jekyll/jekyll-import
permalink: pretty

collections:
  docs:
    output: true
    sort_by: doc_order
  importers:
    output: true

defaults:
  - scope:
      type: docs
    values:
      layout: docs
  - scope:
      type: importers
    values:
      layout: importer
      title_suffix: " Importer"
